create table if not exists community_poll_votes (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    poll_id varchar(80) not null,
    student_id varchar(50) not null,
    option_index integer not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_community_poll_votes_post_poll_student unique (post_id, poll_id, student_id),
    constraint fk_community_poll_votes_post foreign key (post_id) references community_posts(id) on delete cascade
);

create index if not exists idx_community_posts_category_created_at on community_posts(category, created_at desc);
create index if not exists idx_community_posts_author_created_at on community_posts(author_student_id, created_at desc);
create index if not exists idx_community_comments_student_id on community_comments(student_id);
create index if not exists idx_community_post_votes_student_id on community_post_votes(student_id);
create index if not exists idx_community_poll_votes_post_id on community_poll_votes(post_id);
create index if not exists idx_community_poll_votes_student_id on community_poll_votes(student_id);
