CREATE TABLE recruit_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    student_id VARCHAR(10) NOT NULL,
    department VARCHAR(80) NOT NULL,
    grade VARCHAR(50),
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(120) NOT NULL,
    interests TEXT,
    motive TEXT NOT NULL,
    experience TEXT,
    expectation TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    admin_note TEXT,
    client_ip VARCHAR(45),
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_recruit_applications_status ON recruit_applications(status);
CREATE INDEX idx_recruit_applications_submitted_at ON recruit_applications(submitted_at DESC);
