CREATE TABLE IF NOT EXISTS role_permissions (
    role VARCHAR(20) NOT NULL,
    permission VARCHAR(60) NOT NULL,
    allowed BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_by VARCHAR(30),
    PRIMARY KEY (role, permission)
);

INSERT INTO role_permissions (role, permission, allowed) VALUES
    ('ASSOCIATE', 'club_room.view', false),
    ('ASSOCIATE', 'community.anonymous_board', false),
    ('ASSOCIATE', 'community.moderate', false),
    ('ASSOCIATE', 'notice.write', false),
    ('ASSOCIATE', 'activity.write', false),
    ('ASSOCIATE', 'project.write', false),
    ('ASSOCIATE', 'archive.manage', false),
    ('ASSOCIATE', 'site_settings.edit', false),
    ('ASSOCIATE', 'operations.panel', false),
    ('USER', 'club_room.view', true),
    ('USER', 'community.anonymous_board', true),
    ('USER', 'community.moderate', false),
    ('USER', 'notice.write', false),
    ('USER', 'activity.write', false),
    ('USER', 'project.write', false),
    ('USER', 'archive.manage', false),
    ('USER', 'site_settings.edit', false),
    ('USER', 'operations.panel', false),
    ('OFFICER', 'club_room.view', true),
    ('OFFICER', 'community.anonymous_board', true),
    ('OFFICER', 'community.moderate', false),
    ('OFFICER', 'notice.write', true),
    ('OFFICER', 'activity.write', true),
    ('OFFICER', 'project.write', true),
    ('OFFICER', 'archive.manage', false),
    ('OFFICER', 'site_settings.edit', true),
    ('OFFICER', 'operations.panel', true),
    ('VICE_PRESIDENT', 'club_room.view', true),
    ('VICE_PRESIDENT', 'community.anonymous_board', true),
    ('VICE_PRESIDENT', 'community.moderate', true),
    ('VICE_PRESIDENT', 'notice.write', true),
    ('VICE_PRESIDENT', 'activity.write', true),
    ('VICE_PRESIDENT', 'project.write', true),
    ('VICE_PRESIDENT', 'archive.manage', true),
    ('VICE_PRESIDENT', 'site_settings.edit', true),
    ('VICE_PRESIDENT', 'operations.panel', true)
ON CONFLICT (role, permission) DO NOTHING;
